FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install pandas
RUN pip install kafka-python
RUN pip install cassandra-driver
RUN pip install scikit-learn
RUN pip install python-dotenv